name: Build Examples

on:
  push:
    branches: [main]
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        swift:
          - image: swift:6.2.3
            wask-sdk-url: https://download.swift.org/swift-6.2.3-release/wasm-sdk/swift-6.2.3-RELEASE/swift-6.2.3-RELEASE_wasm.artifactbundle.tar.gz
            wasm-sdk-checksum: 394040ecd5260e68bb02f6c20aeede733b9b90702c2204e178f3e42413edad2a
        examples:
          - Examples/Swiftle
          - Examples/Basic
    container: ${{ matrix.swift.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Swift WASM SDK
        run: swift sdk install ${{ matrix.swift.wask-sdk-url }} --checksum ${{ matrix.swift.wasm-sdk-checksum }}

      - name: Build (embedded)
        id: build_embedded
        working-directory: ${{ matrix.examples }}
        continue-on-error: true
        run: ./build.sh

      - name: Build (dev)
        id: build_dev
        working-directory: ${{ matrix.examples }}
        continue-on-error: true
        run: ./build-dev.sh

      - name: Fail if any build failed
        if: ${{ steps.build_embedded.outcome == 'failure' || steps.build_dev.outcome == 'failure' }}
        run: exit 1
